{
	"version": 1582466963,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/tiledbackground.png",
		"images/dino-sheet0.png",
		"images/dino-sheet1.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/stone-sheet0.png",
		"images/crate-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/star-sheet0.png",
		"images/spritefont.png",
		"images/spritefont2.png",
		"images/spritefont4.png",
		"images/tiledbackground2.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/tree_-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite14-sheet0.png",
		"media/title theme - super mario world.m4a",
		"media/title theme - super mario world.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}